import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/page";
import Footer from "./components/footer/page";
import localFont from "@next/font/local";

const inter = Inter({ subsets: ["latin"] });

const Rolinko = localFont({
  src: [
    {
      path: "../public/font/RolinkoTtf.ttf",
      weight: "300",
    },
  ],
  variable: "--font-rolinko",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${Rolinko.variable}`}>
        <div className="w-[1440px]">
          <Navbar></Navbar>
          <main>{children}</main>
          <Footer></Footer>
        </div>
      </body>
    </html>
  );
}
